// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJNP_vXVwTnUrsR_baOaKz_oV-hgnu9w',
    appId: '1:937859878215:web:b1eaf669b614e94b0c1062',
    messagingSenderId: '937859878215',
    projectId: 'group10-a43d1',
    authDomain: 'group10-a43d1.firebaseapp.com',
    storageBucket: 'group10-a43d1.appspot.com',
    measurementId: 'G-7J3SDBJ6KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZe2_Mb55MOU5ToLGyY6jJ1nb9xFqxlMg',
    appId: '1:937859878215:android:3f54025daf2d82b70c1062',
    messagingSenderId: '937859878215',
    projectId: 'group10-a43d1',
    storageBucket: 'group10-a43d1.appspot.com',
  );
}
